name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  GO_VERSION: 1.16

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-test-go-
      - name: Tests
        run: go test -race ./shodan/
